# Generated by Django 3.0.7 on 2021-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Photo', models.FileField(upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
